name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create config.js and .nojekyll
        run: |
          echo "export const config = { apiKey: '${{ secrets.API_KEY }}' };" > docs/config.js
          touch docs/.nojekyll
          cat docs/config.js
          ls docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          exclude_assets: ''